export const experience = [
  {
    id: "bonzark",
    companyName: "Bonzark Technologies",
    joinMonth: "July",
    joinYear: 2022,
    seperationMonth: "November",
    seperationYear: 2023,
    jobTitle: "Full Stack Developer",
    points: [
      "Designed and developed attractive and appealing user interfaces, and implemented front-end functionalities.",
      "Produced RESTful APIs in the back-end to serve data from/to the database and the front-end, used middleware for authentication, validation and varification.",
      "primarily worked with the MERN development stack and NEXT.js to develop fast, responsive and appealing web applications.",
      "Worked on php, .net and python project on secondary bases for implementing small functionalities and bug fixes.",
      "Communicated with clients on regular bases for daily updates and future descissions.",
    ],
  },
  {
    id: "hdm",
    companyName: "Health Data Max (HDM)",
    joinMonth: "February",
    joinYear: 2024,
    seperationMonth: "Present",
    seperationYear: "",
    jobTitle: "Software Developer - Full Stack",
    points: [
      "Developed responsive UI screens based on Figma references given, and implemented all related functionalities, and represented API response data in several forms using ReactJS & MaterialUI.",
      "Developed RESTful APIs using NodeJs & ExpressJS to query MongoDB database and serve an appropriate response.",
      "Migrated NodeJs APIs from using DynamoDB & Elasticsearch into using MongoDB for a single central database, and easier, and more performance efficient querying.",
      "Led a small team in a technology migration mission for migrating the entire back-end from NodeJs to FASTapi tech stack.",
      "Took ownership of the entire front-end of the HDM App. ",
      "Communicated and collaborated with the team in a remote environment to kept updated with the developments.",
    ],
  },
];
