export const experience = [
  {
    id: "xora",
    companyName: "Xora",
    joinMonth: "March",
    joinYear: 2025,
    seperationMonth: "June",
    seperationYear: 2025,
    jobTitle: "Front End Developer",
    points: [
      "Solely developed a complex and inteutive proposal builder module with rich text editing capabilities, section adding features and reorganizing features.",
      "Implemented a Kanban-style task board managing module single handedly wbility to handle hundreds of tasks a an organization",
      "Caried out regorous testing and bug fixing while collaborating with cross-functional teams and lead the front end web portal.",
      "Used several ai tools like Calude and chat gpt to speed up development and boost system performance with prompt engineering",
    ],
  },
  {
    id: "hdm",
    companyName: "Health Data Max Innovations",
    joinMonth: "February",
    joinYear: 2024,
    seperationMonth: "February",
    seperationYear: 2025,
    jobTitle: "Software Developer",
    points: [
      "Organized and implemented a healthcare-focused coding compliance platform that improved diagnostic coding accuracy, increasing reimbursement efficiency by 25% in six months.",
      "Led and mentored a team through project cycles to build compliance tools, delivering three key system performance enhancements.",
      "Managed and prioritized 50+ Jira stories, collaborating with cross-functional teams to align deliverables with business goals, improving project efficiency by 20%.",
      "Engineered an interactive PDF rendering solution using HTML components, reducing rendering time by 30%, and created an adaptive tabular-list component that improved data visualization for 100+ users.",
      "Took ownership of the entire front-end of the HDM App. ",
      "Led a team in technology migration mission for the entire back-end from NodeJs to FASTapi and further development.",
      "Communicated and collaborated with the team in a remote environment to keep updated with the developments.",
      "Developed responsive UI screens based on Figma references given, and implemented all related functionalities, and represented API response data in several forms using ReactJS & MaterialUI.",
      "Developed RESTful APIs using NodeJs & ExpressJS to query MongoDB database and serve an appropriate response.",
      "Migrated NodeJs APIs from using DynamoDB & Elasticsearch into using MongoDB for a single central database, and easier, and more performance efficient querying.",
    ],
  },
  {
    id: "bonzark",
    companyName: "Bonzark Technologies",
    joinMonth: "July",
    joinYear: 2022,
    seperationMonth: "November",
    seperationYear: 2023,
    jobTitle: "Full Stack Developer",
    points: [
      "Developed and maintained scalable web applications using the MERN stack, ensuring 99.9% uptime and seamless performance under high traffic.",
      "Introduced new API endpoints and optimized database queries as the most junior member on the team, increasing system performance to support seamless processing for over one million monthly active users.",
      "Conducted rigorous testing and debugging, collaborating with clients to deliver error-free solutions, achieving a 95% client satisfaction rate.",
      "Worked on php, .net and python project on secondary bases for implementing small functionalities and bug fixes.",
      "Communicated with clients on regular bases for daily updates and future descissions.",
    ],
  },
];
