import {
  faBootstrap,
  faCss3Alt,
  faFigma,
  faGithub,
  faGitlab,
  faHtml5,
  faJava,
  faJira,
  faJs,
  faNode,
  faPhp,
  faPython,
  faReact,
  faSass,
  faSlack,
  faSquareGit,
  faUikit,
} from "@fortawesome/free-brands-svg-icons";

import {
  faCode,
  faComments,
  faDatabase,
  faFire,
  faHeadset,
  faLaptopMedical,
  faMobileScreenButton,
  faPenFancy,
  faPlusMinus,
  faPuzzlePiece,
  faRectangleAd,
  faShuffle,
  faStopwatch,
  faUsersGear,
} from "@fortawesome/free-solid-svg-icons";

export const techSkills = [
  { icon: "", id: "nextjs", text: "NEXT.js" },
  { icon: faReact, id: "react", text: "React.js" },
  { icon: faNode, id: "node", text: "Node.js" },
  { icon: faHtml5, id: "html", text: "HTML" },
  { icon: faCss3Alt, id: "css", text: "CSS" },
  { icon: faJs, id: "js", text: "JavaScript" },
  { icon: "", id: "typescript", text: "TypeScript" },
  { icon: faBootstrap, id: "bootstrap", text: "Bootstrap" },
  { icon: "", id: "tailwind", text: "Tailwind CSS" },
  { icon: faSass, id: "sass", text: "SASS" },
  { icon: faUikit, id: "mui", text: "MaterialUI" },
  { icon: "", id: "express", text: "Express.js" },
  { icon: faSquareGit, id: "git", text: "Git" },
  { icon: faDatabase, id: "sql", text: "SQL" },
  { icon: faCode, id: "nosql", text: "NoSQL" },
  { icon: faGithub, id: "github", text: "GitHub" },
  { icon: faGitlab, id: "gitlab", text: "GitLab" },
  { icon: "", id: "photoshop", text: "Photoshop" },
  { icon: "", id: "illustrator", text: "Illustrator" },
  { icon: faFigma, id: "figma", text: "Figma" },
  { icon: "", id: "dotnet", text: "ASP.NET/Core" },
  { icon: faPython, id: "python", text: "Python" },
  { icon: faPhp, id: "php", text: "PHP" },
  { icon: faJava, id: "java", text: "Java" },
  { icon: "", id: "claude", text: "Claude" },
  { icon: faJira, id: "jira", text: "Jira" },
  { icon: faSlack, id: "slack", text: "Slack" },
  { icon: "", id: "teams", text: "Teams" },
  { icon: "", id: "graphql", text: "GraphQL" },
  { icon: "", id: "redux", text: "Redux" },
  { icon: faFire, id: "fcm", text: "FCM" },
];

export const softSkills = [
  {
    icon: faMobileScreenButton,
    id: "responsive",
    text: "Responsive Web Design",
  },
  { icon: faRectangleAd, id: "promptengineering", text: "Prompt Engineering" },
  { icon: faComments, id: "communication", text: "Impeccable Communication" },
  { icon: faUsersGear, id: "teamleading", text: "Team Leading" },
  { icon: faPuzzlePiece, id: "problemsloving", text: "Problem Solving" },
  { icon: faStopwatch, id: "timemanagement", text: "Time Management" },
  { icon: faPlusMinus, id: "adaptive", text: "Adaptive" },
  { icon: faShuffle, id: "flexiblity", text: "Flexibility" },
  { icon: faPenFancy, id: "writing", text: "Content Writing" },
  { icon: faLaptopMedical, id: "support", text: "Supportive" },
];
